/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  CY
 * Created: Mar 14, 2023
 */

CREATE TABLE CUSTOMER (ID CHAR(36) NOT NULL, USERNAME VARCHAR(50) NOT NULL, PASSWORDHASH VARCHAR(100) NOT NULL, EMAIL VARCHAR(50) NOT NULL, FULLNAME VARCHAR(50) NOT NULL, CONTACT VARCHAR(50) NOT NULL, ADDRESS VARCHAR(50) NOT NULL, DATEJOIN DATE, PROFILEIMGTYPE VARCHAR(20), PROFILEIMG LONG VARCHAR, PRIMARY KEY (ID));


CREATE TABLE EMPLOYEE (ID CHAR(36) NOT NULL, USERNAME VARCHAR(50) NOT NULL, PASSWORDHASH VARCHAR(50) NOT NULL, EMAIL VARCHAR(50) NOT NULL, FULLNAME VARCHAR(50) NOT NULL, CONTACT VARCHAR(50) NOT NULL, ADDRESS VARCHAR(50) NOT NULL, USERTYPE VARCHAR(10) NOT NULL, DATEJOIN DATE, PROFILEIMGTYPE VARCHAR(20), PROFILEIMG LONG VARCHAR, PRIMARY KEY (ID));

CREATE TABLE CART (CARTID INTEGER NOT NULL, CUSTOMERID CHAR(36), PRODUCTID INTEGER, QTY INTEGER, PRIMARY KEY (CARTID));

CREATE TABLE PRODUCT (
    PRODUCTID INTEGER NOT NULL, 
    "NAME" VARCHAR(256), 
    DESCRIPTION VARCHAR(256), 
    CATEGORY VARCHAR(256), 
    PRICE DOUBLE, 
    STOCKQTY INTEGER, 
    IMAGE VARCHAR(256), 
    PRIMARY KEY (PRODUCTID)
);


CREATE TABLE "ORDER" (
    ORDERID INTEGER NOT NULL PRIMARY KEY,
    CUSTID CHAR(36) REFERENCES CUSTOMER("ID"),
    VOUCHERID INTEGER,
    EMPLOYEEID CHAR(36),
    SUBTOTAL DOUBLE,
    TAX DOUBLE,
    DELIVERYCHARGE DOUBLE,
    TOTALPAYMENT DOUBLE,
    PAYMENTMETHOD VARCHAR(100),
    SHIPPINGADDRESS VARCHAR(255),
    STATUS VARCHAR(10),
    ORDERDATE VARCHAR(20)
);