/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  CY
 * Created: Mar 14, 2023
 */

CREATE TABLE CUSTOMER( 
    ID CHAR(36) NOT NULL, 
    USERNAME VARCHAR(50) NOT NULL, 
    PASSWORDHASH VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL, 
    PROFILEIMG BLOB NOT NULL, 
    FULLNAME VARCHAR(50) NOT NULL, 
    CONTACT VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(50) NOT NULL, 
    PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE( 
    ID CHAR(36) NOT NULL, 
    USERNAME VARCHAR(50) NOT NULL, 
    PASSWORDHASH VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL, 
    PROFILEIMG BLOB NOT NULL, 
    FULLNAME VARCHAR(50) NOT NULL, 
    CONTACT VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(50) NOT NULL,
    USERTYPE VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE PRODUCT (
    PRODUCTID INTEGER NOT NULL, 
    "NAME" VARCHAR(256), 
    DESCRIPTION VARCHAR(256), 
    "TYPE" VARCHAR(256), 
    CATEGORY VARCHAR(256), 
    PRICE DOUBLE, 
    STOCKQTY INTEGER, 
    IMAGE BLOB, 
    PRIMARY KEY (PRODUCTID)
);

